config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  
  root to: "posts#index"
  resources :posts do
      collection do
        get 'search'
      end
    end
  resources :keywords do
      collection do
        get 'search'
      end
    end
  resources :titles
end

app/models/keyword.rb
class Keyword < ApplicationRecord

  has_many :titles

  validates :text, {uniqueness: true}

  def self.search(search)
    if search != ""
      Keyword.where('text LIKE(?)', "%#{search}%")
    else
      Keyword.all
    end
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
    def index
      @keywords = Keyword.all.page(params[:page]).per(25).order("created_at DESC")
    end
    
    def search
      @keywords = Keyword.search(params[:keyword])
    end

    def new
      @keyword = Keyword.new
    end
  
    def create  
      @keyword = Keyword.new(keyword_params)
      if @keyword.save
        redirect_to  keywords_path
      else
        render :show  
      end 
    end

    def show
      @keywords = Keyword.all
    end

    def destroy
      @keywords = Keyword.all
      @keyword = @keywords.find(params[:id])
      @keyword.destroy
      redirect_back(fallback_location: keywords_path)
    end

    private
  
    def keyword_params
      params.permit(:text).merge(user_id: current_user.id)
    end  
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/index.html.erb
<div class= "keyword_parent">
  <div class="sp3"></div>
  <marquee direction="doown"><h1 class="line_line2">　　　　　　　</h1></marquee>
  <div class="space">
    <div class="keyword_childe">
      <div class="sp3"></div>
      <div class = "btnd btnd--shadow space">
        <%= form_with model: @keyword, url:keywords_path, method: :post,id: "form" do |f| %>
          <div class="keywordchild">
            <%= f.submit "登録する" ,class:"btnd btnd--shadow aaaa" ,id: "submit" %>
            <div class="sp3"></div>
            <div class="sp3"></div>
          </div> 
        
          <%= f.text_area :text, class:"textpostin textpostin_key", id:"keyword_text", placeholder:"　　登録済みの言葉は登録できません!！" ,size: "40x5",rows:"7" ,maxlength:"140" %>
        <% end %>
        <div class="sp3"></div>
      </div>
    </div> 
  </div> 
  <div class="sp3"></div>
  <div class="sp3"></div>
    <div class="keyword_childe">
      <div class= "keyword_list">
        <% @keywords.each do |word| %>
          <%= "#{word.text} / "%>
        <% end %>
        <div class = "page_list">
          <%= paginate @keywords %>
        </div> 
      </div>
    </div>
    <marquee direction="right"><h1 class="line_line2">　　　　　　　</h1></marquee>
    <div class="sp3"></div>
      <div class = "keyword_root">
      
        <%=link_to '言葉の編集',keyword_path(@keywords), class:" btnd btnd--shadow",id: "submit" %> 
        <%=link_to 'home', root_path, class:" btnd btnd--shadow",id: "submit" %> 
      </div>  
</div>

app/views/keywords/search.html.erb
<div class="search_post">
    <div class="sp3"></div>
    <div class= "this"> 
      <marquee direction="doown"><h5 class="line_line2">　　　　　　　</h1></marquee>
    </div>
    <div class="sp3"></div>
    <div class="sp3"></div>
    <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "　　みんなの無駄を検索みよう", class: "textpostin textpostina" ,size: "30x10" %>
        <%= form.submit "search", class: "btnda btnd--shadowa" %>
    <% end %>
    <div class="word_edit_list">
      <% @keywords.each do |word| %>
        <%=link_to '【delete】', keyword_path(word.id),method: :delete, class:"btnda btnd--shadowa" %>
        <p><%= "#{word.text} / "%></p>
      <% end %>
    </div>
   <div class="sp3"></div>
   <div class="sp3"></div>
    <div class= "this"> 
      <marquee direction="right"><h5 class="line_line2">　　　　　　　</h1></marquee>
    </div>
    <div class ="btnd btnd--shadow showfooter showfootera">
      <%=link_to 'home', root_path, class:"btnd btnd--shadow" %>
    </div>
</div>    

app/views/keywords/show.html.erb
<div class= "word_edit">
  <div class="sp4">
    <marquee direction="doown"><h1 class="line_line">　　　　　　　</h1></marquee>
  </div>
  <%= form_with(url: search_keywords_path(@keywords.ids), local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "　　言葉の検索", class: "textpostin textpostina" ,size: "30x10" %>
    <%= form.submit "search", class: "btnda btnd--shadowa" %>
  <% end %>
  <div class="word_edit_list">
    <% @keywords.each do |word| %>
      <%= "#{word.text} / "%>
    <% end %>
  </div>
  <div class="sp4">
    <marquee direction="right"><h1 class="line_line">　　　　　　　</h1></marquee>
  </div>
    <%=link_to 'home', root_path, class:"btnda btnd--shadowa" %> 
</div>