config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  
  root to: "posts#index"
  resources :posts do
      collection do
        get 'search'
      end
    end
  resources :keywords do
      collection do
        get 'search'
      end
    end
  resources :titles
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  belongs_to :decoration
  has_many :titles

  validates :text, presence: true

  def self.search(search)
    if search != ""
      Post.where('text LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.page(params[:page]).per(10).order("created_at DESC")
    @random = Keyword.order("RAND()").limit(2)
  end

  def search
    @posts = Post.search(params[:keyword])
    
  end

  def new
    @post = Post.new
    @random = Keyword.order("RAND()").limit(2)
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to post_path(@post.id)
    end
  end

  def show
    @post = Post.find(params[:id])
  end


  private

  def post_params
    params.require(:post).permit(:text).merge(user_id: current_user.id)
  end

  def titles
    @random = Keyword.order("RAND()").limit(2)
    @random.each do |book|
      book.text
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def titles
    @random = Keyword.order("RAND()").limit(2)
    @add = []
    @random.each do |book|
      @add << book.text
    end
  end
end 

app/views/posts/index.html.erb
<div class="top-wrapper">
  <div class ="sp5"></div> 
  <div class= "indextop">
    <h1 class="line_line">　　　　　　　</h1>
  </div>
  <div class= "glass1">
    <h1>
      <span
      class="txt-rotate"
      data-period="2000"
      # data-rotate='[ "言葉を新たに創造せよ", "言葉の概念をひっくり返せ", "役割から考える新しい言葉", "考える術", "表現を楽しめ!!" ,"無駄づくり"]'></span> 
    </h1>
  <script>
    var TxtRotate = function(el, toRotate, period) {
      this.toRotate = toRotate;
      this.el = el;
      this.loopNum = 0;
      this.period = parseInt(period, 10) || 2000;
      this.txt = '';
      this.tick();
      this.isDeleting = false;
    };

    TxtRotate.prototype.tick = function() {
      var i = this.loopNum % this.toRotate.length;
      var fullTxt = this.toRotate[i];

      if (this.isDeleting) {
        this.txt = fullTxt.substring(0, this.txt.length - 1);
      } else {
        this.txt = fullTxt.substring(0, this.txt.length + 1);
      }

      this.el.innerHTML = '<span class="wrap">'+this.txt+'</span>';

      var that = this;
      var delta = 300 - Math.random() * 100;

      if (this.isDeleting) { delta /= 2; }

      if (!this.isDeleting && this.txt === fullTxt) {
        delta = this.period;
        this.isDeleting = true;
      } else if (this.isDeleting && this.txt === '') {
        this.isDeleting = false;
        this.loopNum++;
        delta = 500;
      }

      setTimeout(function() {
        that.tick();
      }, delta);
    };

    window.onload = function() {
      var elements = document.getElementsByClassName('txt-rotate');
      for (var i=0; i<elements.length; i++) {
        var toRotate = elements[i].getAttribute('data-rotate');
        var period = elements[i].getAttribute('data-period');
        if (toRotate) {
          new TxtRotate(elements[i], JSON.parse(toRotate), period);
        }
      }
      // INJECT CSS
      var css = document.createElement("style");
      css.type = "text/css";
      css.innerHTML = ".txt-rotate > .wrap { border-right: 0.08em solid #666 }";
      document.body.appendChild(css);
    };
  </script>
  <div class ="sp5"></div> 
    
  </div>
  <div class="indexsp">
    <h1 class="line_line">　　　　　　　</h1>
  </div>
  <div class ="about">
        <div class ="sp5"></div> 
        <div class ="sp5"></div> 
        <h3 class="about_a">"How About"</h3>
        <h4>商品名：KotobaOCKTAIL</h4>
        <h5>(読み方：カクテル）<h5>
        <p>このアプリケーションを考案したきっかけは映画「僕たちは世界を変えることができない。」を見た時に思いつきました。
            こちらの映画は世界を変えることは大きすぎてできないけど目標のカンボジアに学校をつくることができると自分の見える世界が変わり未来に向かっていくストーリーです。
        </p>
        <p>コロナ禍を迎え、今までの当然が当然ではなくなり常識が覆される事(ex:リモートワークの常習化、飲食店の20時までの営 業、事ある度にアルコール消毒など)も頻繁に起きるようになりました。
        </p>
        <p>私の勤めていた飲食業界のもれなくコロナ禍のダメージを受けた業界の一つです。
        「コロナ禍を変えたい」や「飲食業界を変えたい」はあまりにも大きな課題過ぎますし、変えるための術も思いついていません・・・。</p>
        <p>そこで上記の映画のように世界は変わらないけど、自分の視野(発想力)を変えれるようなアプリケーションを作成しようとかんがえました。</p>
        <p>そんなことを考えている時に出会った本「考える術」(著:藤原麻里菜）を実践できるようなアプリケーションを作成作成しようと思い実装に取り組みました</p>
        <p>既にある既存の言葉と言葉で誕生したお題に効能や意味・役割を与えることを習慣できるアプリケーションです。
        「カメラ」×「携帯電話」＝「写メ」のようにかなり離れているものがか繋がることで人々の生活が、ライフスタイルが変わることもあるのです。</p>
        <p>アプリケーションの命名は、既存のリキュールやスピリッツを様々な組み合わせで世界中の大人を魅了しているカクテルのように、既存の言葉たちを組み合わせて新しい世界観で魅了できる時が来ればいいなと思い名付けました。無駄なように思っていた言葉も意味や役割も、様々な人に触れて、積み重なることによって、世界が変わるような表現が・役割を持つ日がいつか来るのかもしれません・・・。
        </p>
      </div>
        <div class ="sp5"></div> 
  <div > 
    <marquee direction="doown"><h5 class="line_line2">　　　　　　　</h1></marquee>
  </div>
  <div class ="sp5"></div>
  <h1 class="head_test">考える術</h1>
  <div class="glass2">
    <h1>
      <span
      class="txt-rotate"
      data-period="2000"
      data-rotate='[ "|1|「言葉」から考える","-高速で新しいものを生み出す術","|2|半径1メートルから考える","-モヤモヤを有効活用する術","|3|ひねくれて考える","-視点をサクサク切り替える術","|4|「みんなが知っていること」から考える","-一人だけ違うことをする術","|5|「自分のこと」から考える","-心の叫びをかたちにする術","|6|「情報」から考える","-全然考えたことのないことを思いつく術","|7|「感情」から考える","-自分らしさを全開にする術"]'></span>
    </h1>
    <script>
      var TxtRotate = function(el, toRotate, period) {
        this.toRotate = toRotate;
        this.el = el;
        this.loopNum = 0;
        this.period = parseInt(period, 10) || 2000;
        this.txt = '';
        this.tick();
        this.isDeleting = false;
      };

      TxtRotate.prototype.tick = function() {
        var i = this.loopNum % this.toRotate.length;
        var fullTxt = this.toRotate[i];

        if (this.isDeleting) {
          this.txt = fullTxt.substring(0, this.txt.length - 1);
        } else {
          this.txt = fullTxt.substring(0, this.txt.length + 1);
        }

        this.el.innerHTML = '<span class="wrap">'+this.txt+'</span>';

        var that = this;
        var delta = 300 - Math.random() * 100;

        if (this.isDeleting) { delta /= 2; }

        if (!this.isDeleting && this.txt === fullTxt) {
          delta = this.period;
          this.isDeleting = true;
        } else if (this.isDeleting && this.txt === '') {
          this.isDeleting = false;
          this.loopNum++;
          delta = 500;
        }

        setTimeout(function() {
          that.tick();
        }, delta);
        };

        window.onload = function() {
          var elements = document.getElementsByClassName('txt-rotate');
          for (var i=0; i<elements.length; i++) {
            var toRotate = elements[i].getAttribute('data-rotate');
            var period = elements[i].getAttribute('data-period');
            if (toRotate) {
              new TxtRotate(elements[i], JSON.parse(toRotate), period);
            }
          }
          // INJECT CSS
          var css = document.createElement("style");
          css.type = "text/css";
          css.innerHTML = ".txt-rotate > .wrap { border-right: 0.08em solid #666 }";
          document.body.appendChild(css);
        };
        </script> 
</div>
 
  <div class="how">
    <span class="about">
      <h4>"How to use"</h4>
    </span>
      <p>既に登録されている単語がランダム2つ選ばれお題が決まります。</p>
      <p>ランダムで組み合わされた新しい"造語"の役割を考えて投稿してください</p>
      <p>ありえないと思う発想から今使われているモノで世の中は埋もれています</p>
      <p>ここから生まれたアイディアが誰かの人生を変えるキッカケになるかもしれません</p>
  </div>
  <div class="keyord_rootmain">
    <div class="keyword_root">
      <%= link_to( keywords_path , class: 'btnda btnd--shadowa') do %>
        <span class=''>言葉を登録する</span>
      <% end %>
  </div>

  <div class="keyword_root" >
    <%= form_with model: @post, url:posts_path, method: :post, local: true do |f| %>
      <%= link_to(new_post_path , class: 'btnda btnd--shadowa') do %>
        <span class=''>投稿する</span>
      <% end %>
    <% end %>
  </div>
  <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "　みんなの無駄を検索してみよう", class: "textpostin textpostina" ,size: "30x10" %>
    <%= form.submit "search", class: "btnda btnd--shadowa" %>
  <% end %>

  <div class= "this"> 
    <marquee direction="right"><h5 class="line_line2">　　　　　　　</h1></marquee>
  </div>
  <div class ="list_list">
    <div class = "list" >
      <% @posts.each do |post| %>
        <li>
          <ul><%= link_to "● #{post.text}", post_path(post), class: "listul" %></ul>
        </li>
      <% end %>
      <div class = "page">
        <%= paginate @posts %>
      </div>  
    </div> 
  </div>   

    

app/views/posts/new.html.erb
<div class="new_post">
  <%# 投稿機能 %>
  <div class="sp4"></div>
  <div class= "this"> 
    <marquee direction="right"><h5 class="line_line2">　　　　　　　</h1></marquee>
  </div>
  <div class="post_tweet">
    <div class="yourorder">
      <h3>New word is ・・・</h3>
      <% @random.each do |book| %>
        <span class="yourorderlist"><%= book.text %></span>
      <% end %>  
        <% titles %>
    </div>
    <div class="keyword_root"> 
      <%=link_to 'word change', new_post_path , class:"btnd btnd--shadow" %>
    </div>  
    <marquee direction="doown"><h1 class="line_line2">　　　　　　　</h1></marquee>
    <div class="count_time">
      <div class="timemain">
        <div class ="buttons keyword_root ">
          <div class="sp2 ">
            <button id ="startbutton" class="btnd btnd--shadow">start</button>
          </div> 
          <div class="sp2">
            <button id ="stopbutton" class="btnd btnd--shadow">stop</button>
          </div> 
          <div class="sp2">
            <button id ="resetbutton" class="btnd btnd--shadow">reset</button>
          </div> 
        </div>    
    </div>
    <div class ="timerbody">
      <div class = "timer">
        <h3>Time to think</h3>
          <div id ="timer" class= "timer"></div>
      </div>  
    </div>

    <script>
      var start_flag = false;
      var intervalid;
      var to_timeup = 300;
      var backstart = 300;

      function count_start() {
        if (start_flag===false) {
          intervalid = setInterval(count_down, 1000);
          start_flag = true;
          }
        }

        function count_down() {
          var timer = document.getElementById("timer");
          if (to_timeup===0) {
            $('#timer').html('Time up!');  
            $('#timer').addClass('red');
            count_stop();
          } else {
            to_timeup--;
            padding();
          }
        }

        function count_stop() {
          clearInterval(intervalid);
          start_flag = false;
        }

        function count_reset() {
          var timer = document.getElementById("timer");
            to_timeup = backstart;
            padding();
            // timer.style.color="black"; 
            $('#timer').css('color','black');
            clearInterval(intervalid);
            start_flag = false;
        }

        function padding() {
          var min = 0;
          var sec = 0;
          var timer = document.getElementById("timer");
              min = Math.floor(to_timeup/60);
              sec = (to_timeup%60);
              min = ('0'+min).slice(-2);
              sec = ('0'+sec).slice(-2);
              timer.innerHTML = min+':'+sec;
        }

        $(function () {
          padding();
          $("#startbutton").click(count_start);
          $("#stopbutton").click(count_stop);
          $("#resetbutton").click(count_reset);
        })
    </script>
    <script type=”text/JavaScript” src=”js/main.js”></script>
  </div>

  <%= form_with model: @post, url:posts_path, method: :post, local: true do |f| %>
    <div class="expressparent">
      <div class = "express">
        <h2>Let's express it!!!</h2> 
        <h5>困った時は下記の</h5>
        <h5>装飾語を付けて</h5> 
        <h5>考えてみよう</h5>
        <div class="sp3"></div>
        <div class="btnd btnd--shadow">
          <%= f.submit "投稿する" ,class:"btnd btnd--shadow" %>
          <%=link_to 'home', root_path, class:"btnd btnd--shadow" %> 
        </div>
      </div>
      <div class="textpost" >
        <%= f.text_area :text, class:"textpostin textpostin_post", id:"post_text", value:"New word：#{@add[0]} #{@add[1]} /meaning :" ,rows:"7" ,maxlength:"140",size: "40x8" %>  
      </div> 
    </div>
  <% end %>
  <div class= "this"> 
    <marquee direction="right"><h5 class="line_line2">　　　　　　　</h1></marquee>
  </div>   
  <h1>装飾語</h1>
  <h1>
    <span
      class="txt-rotate"
      data-period="2000"
      data-rotate='[ "華麗な", "夢のような", "恐ろしく", "追いかけてくる", "笑えない" ,"まるで","嘘みたいな","とてつもなく","信じられない","生まれたてのような"]'></span>
  </h1>
<script>
  var TxtRotate = function(el, toRotate, period) {
    this.toRotate = toRotate;
    this.el = el;
    this.loopNum = 0;
    this.period = parseInt(period, 10) || 2000;
    this.txt = '';
    this.tick();
    this.isDeleting = false;
  };

  TxtRotate.prototype.tick = function() {
    var i = this.loopNum % this.toRotate.length;
    var fullTxt = this.toRotate[i];

    if (this.isDeleting) {
      this.txt = fullTxt.substring(0, this.txt.length - 1);
    } else {
      this.txt = fullTxt.substring(0, this.txt.length + 1);
    }

    this.el.innerHTML = '<span class="wrap">'+this.txt+'</span>';
    var that = this;
    var delta = 300 - Math.random() * 100;

    if (this.isDeleting) { delta /= 2; }

    if (!this.isDeleting && this.txt === fullTxt) {
      delta = this.period;
      this.isDeleting = true;
    } else if (this.isDeleting && this.txt === '') {
      this.isDeleting = false;
      this.loopNum++;
      delta = 500;
    }

    setTimeout(function() {
      that.tick();
    }, delta);
  };

  window.onload = function() {
    var elements = document.getElementsByClassName('txt-rotate');
    for (var i=0; i<elements.length; i++) {
      var toRotate = elements[i].getAttribute('data-rotate');
      var period = elements[i].getAttribute('data-period');
      if (toRotate) {
        new TxtRotate(elements[i], JSON.parse(toRotate), period);
      }
    }
    // INJECT CSS
    var css = document.createElement("style");
    css.type = "text/css";
    css.innerHTML = ".txt-rotate > .wrap { border-right: 0.08em solid #666 }";
    document.body.appendChild(css);
  };
</script>

app/views/posts/search.html.erb
<div class="search_post">

  <div class= "this"> 
    <marquee direction="doown"><h5 class="line_line2">　　　　　　　</h1></marquee>
  </div>
  <div class ="list_list">
    <div class = "list" >
      <% @posts.each do |post| %>
        <li>
          <ul><%= link_to "● #{post.text}", post_path(post), class: "listul" %></ul>
        </li>
      <% end %>
    </div> 
  </div>
  <div class= "this"> 
    <marquee direction="right"><h5 class="line_line2">　　　　　　　</h1></marquee>
  </div>
  <div class ="btnd btnd--shadow showfooter showfootera">
    <%=link_to 'home', root_path, class:"btnd btnd--shadow" %>
  </div>
</div>    

app/views/posts/show.html.erb
<div class="tweet_show">
  <div class= "this"> 
    <marquee direction="doown"><h5 class="line_line2">　　　　　　　</h1></marquee>
  </div>
  <div class= "tweet">
      <span class ="here"><%= "#{@post.text}"%><span>
  </div>
  <div class= "this"> 
    <marquee direction="right"><h5 class="line_line2">　　　　　　　</h1></marquee>
  </div>
  <div class ="show_footer"> 
    <div class =" btnd btnd--shadow showfooter">
      <span class="fa fa-twitter btnd btnd--shadow">
        <%= link_to '　tweetする', "https://twitter.com/share?url=#{request.url}/&text=KOCKTAIL/&hashtags=無駄づくり/&hashtags=考える術", title: 'Twitter', target: '_blank',class: "tweeta"%>
      </span>
    </div>
    <div class ="btnd btnd--shadow showfooter showfootera">
      <%=link_to 'home', root_path, class:"btnd btnd--shadow" %>
    </div> 
  </div> 
</div>